// <auto-generated />
using System;
using GentleExpress.Repositories.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GentleExpress.Repositories.EfCore.Migrations
{
    [DbContext(typeof(GentleExpressPostgresDbContext))]
    [Migration("20240707110937_AddDeliveryDates")]
    partial class AddDeliveryDates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GentleExpress.Repositories.Abstraction.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("GentleExpress.Repositories.Abstraction.Entities.Courier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Couriers");
                });

            modelBuilder.Entity("GentleExpress.Repositories.Abstraction.Entities.Delivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AcceptDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CargoReceivalDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ChargeDeliveryFee")
                        .HasColumnType("boolean");

                    b.Property<bool>("ChargeParcelPrice")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeliveryCode")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DesiredPickUpDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ParcelDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("ParcelPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("PickUpAssignmentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PickUpCourierId")
                        .HasColumnType("integer");

                    b.Property<string>("ReceiverAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReceiverDistrictId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReceiverFillDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReceiverNotes")
                        .HasColumnType("text");

                    b.Property<string>("ReceiverPhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("RejectDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VendorAddressId")
                        .HasColumnType("integer");

                    b.Property<string>("VendorNotes")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PickUpCourierId");

                    b.HasIndex("ReceiverDistrictId");

                    b.HasIndex("VendorAddressId");

                    b.ToTable("Deliveries");
                });

            modelBuilder.Entity("GentleExpress.Repositories.Abstraction.Entities.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("GentleExpress.Repositories.Abstraction.Entities.Vendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber1")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber2")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("VendorWalletAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("GentleExpress.Repositories.Abstraction.Entities.VendorAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DistrictId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("boolean");

                    b.Property<int>("VendorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("VendorId");

                    b.ToTable("VendorAddresses");
                });

            modelBuilder.Entity("GentleExpress.Repositories.Abstraction.Entities.Delivery", b =>
                {
                    b.HasOne("GentleExpress.Repositories.Abstraction.Entities.Courier", "PickUpCourier")
                        .WithMany()
                        .HasForeignKey("PickUpCourierId");

                    b.HasOne("GentleExpress.Repositories.Abstraction.Entities.District", "ReceiverDistrict")
                        .WithMany()
                        .HasForeignKey("ReceiverDistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GentleExpress.Repositories.Abstraction.Entities.VendorAddress", "VendorAddress")
                        .WithMany()
                        .HasForeignKey("VendorAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PickUpCourier");

                    b.Navigation("ReceiverDistrict");

                    b.Navigation("VendorAddress");
                });

            modelBuilder.Entity("GentleExpress.Repositories.Abstraction.Entities.District", b =>
                {
                    b.HasOne("GentleExpress.Repositories.Abstraction.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("GentleExpress.Repositories.Abstraction.Entities.VendorAddress", b =>
                {
                    b.HasOne("GentleExpress.Repositories.Abstraction.Entities.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GentleExpress.Repositories.Abstraction.Entities.Vendor", "Vendor")
                        .WithMany("Addresses")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("GentleExpress.Repositories.Abstraction.Entities.Vendor", b =>
                {
                    b.Navigation("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
